### ISSUE TITLE
Feature: Ability to refetch data from the Spotify DBUS

### ISSUE THREAD

**Issue by jlnostr** [goktug97/yet-another-spotify-lyrics#3]
Hey,
nice tool that you've programmed. However, I'd like to have it open at a longer time and therefore kinda refresh the data. For example, when I open the next song in the playlist, I'd like to show the lyrics for that too.

Now I need to quit the program and restart it, would like to have a keyboard shortcut (maybe combine with refresh (key R) too?). It would be even better if the app would listen to changes in the DBUS automatically :)

**Comment by goktug97** [comment]
Will do that in approximately 2 hours. After lunch

**Comment by goktug97** [comment]
Done.

Now it will automaticly refresh the lyrics. Also you can control spotify with in the application
