### ISSUE TITLE
Add compatibility with Spotify Connect

### ISSUE THREAD

**Issue by jlnostr** [goktug97/yet-another-spotify-lyrics#4]
When using Spotify Connect, the DBUS metadata seems to be empty. (why spotify, why?!) The only given properties are the `mpris:trackid`, for example  `spotify:track:1o1rXP16H9JOFfMLkxy8zW` and the `mpris:url` (e.g. `https://open.spotify.com/track/1o1rXP16H9JOFfMLkxy8zW`).

It would be possible to extract the required information using the Spotify API, however this would increase the complexity (where to load/store the API keys, etc.). Nevertheless, it would be a nice feature to have.

**Comment by goktug97** [comment]
If you are using spotifyd can you look at this.
https://github.com/Spotifyd/spotifyd/blob/master/README.md#feature-flags

I really don’t want to add any API related stuff as it requires to create application from the spotify which makes it harder to setup for the end user.

**Comment by jlnostr** [comment]
Never used it before, tried it out yesterday. Unfortunately that doesn't help as the device I'm playing my music on is a wireless speaker.

Future proposal: Generalize the metadata sources to allow different sources for artist/track/etc. But yes, as you've already mentioned, this could make it harder to setup for the end user.

**Comment by goktug97** [comment]
To add a new source, you can implement a different Spotify class.

Spotify connect might be using different name for the dbus interface, can you look for 
available dbus services. If you find something that resembles spotify you can substitute that in to Spotify class
