### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by fipsthedog** [goktug97/yet-another-spotify-lyrics#5]
When running it constantly uses around 15%. How does that come?
Running on arch on an i7.
Thank you!

**Comment by goktug97** [comment]
I decreased the CPU usage in the latest version. If you are using old version can you update it and try again. On my Arch i5 machine I get %15 CPU usage while using it and %4 in IDLE
```bash
pip3 install yet-another-spotify-lyrics --upgrade
```
Commit: https://github.com/goktug97/yet-another-spotify-lyrics/commit/51a11931454e906a8d1822899b25c64ff50dd77b

**Comment by fipsthedog** [comment]
Perfect thank you! <3

**Comment by goktug97** [comment]
Thank you for the feedback
