### ISSUE TITLE
Album Art not downloading

### ISSUE THREAD

**Issue by groovykiwi** [goktug97/yet-another-spotify-lyrics#7]
The album art doesn't show up in terminal. I tried st and urxvt but no luck on both.  
The .cache/spotify-lyrics/ folder does have the artist name and their lyrics but the album_arts subfolders are empty.  
I suppose it has something to do with the downloading process and not the displaying as ueberzug works fine on my system.

**Comment by goktug97** [comment]
Thanks for bringing this to my attention, I will look in to it

**Comment by goktug97** [comment]
It seems the art url given by the spotify dbus is no longer valid. Now the program retrieves the images from a different location and should be working.

**Comment by groovykiwi** [comment]
Yes it's working now ! Thanks for the quick fix. I'm closing the issue.
