### ISSUE TITLE
Spotifyd compitability?

### ISSUE THREAD

**Issue by PoSayDone** [goktug97/yet-another-spotify-lyrics#8]
Is there any way to use this program with spotifyd?

**Comment by PoSayDone** [comment]
The spotify-lyrics trying to find "org.mpris.MediaPlayer2.spotify", but it need to use "org.mpris.MediaPlayer2.spotifyd". How I could change this?

**Comment by goktug97** [comment]
You should update `Spotify` class. 
https://github.com/goktug97/yet-another-spotify-lyrics/blob/master/utils.py#L65

**Comment by PoSayDone** [comment]
Thanks a lot! I love you!
